### PR TITLE
Remove dummy GPU and battery temperature

### PR DESCRIPTION
**Pull request by cyxlily**
Remove dummy GPU and battery temperature.

### CODE REVIEW

**Review by vilasrk — APPROVED** [review]
LGTM

**Review by balajim001 — APPROVED** [review]
LGTM

**Review by JeevakaPrabu — CHANGES_REQUESTED** [review]
please add Tests done to commit message

**Comment by cyxlily** [comment]
> please add Tests done to commit message

Verified on EB: 
https://ubit-artifactory-or.intel.com/artifactory/cactus-absp-or-local/celadon_umr0_master-eng/247/r2_base_aaos/userdebug/

VTS and CTS passed. Attached test reports to jira.

**Review by JeevakaPrabu — APPROVED** [review]

**Pull request merged**
